vich_uploader:
    db_driver: orm

    mappings:
        pulse_images:       
           uri_prefix: /images/pulse
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
